export class Road {
    /// The lengths of straight segments of the road, generated by calling `generateSegments`
    segments: number[];

    constructor(
        public length: number,
        public roadCurveProbability: (straightLength: number) => number,
    ) {
        this.segments = this.generateSegments();
    }

    /**
     * Generate the straight segments of the road.
     */
    generateSegments(): number[] {
        const segments = [];

        let currentLength = 1;
        let currentSegmentLength = 1;
    
        while (currentLength < this.length) {
            const prob = this.roadCurveProbability(currentSegmentLength);
    
            if (Math.random() < prob) {
                // Road should curve
                segments.push(currentSegmentLength);
                currentSegmentLength = 1;
            } else {
                // Go straight
                currentSegmentLength++;
            }
            currentLength++;
        }

        segments.push(currentSegmentLength);

        return segments;
    }
}